const animalData = [
    {
    user_id: "",
    animal_photo: "http://lorempixel.com/200/200",
    animal_type: "Dog",
    microchip: "abc123456789",
    name: "Budweiser",
    age: 1.5,
    gender: "Male",
    primary_breed: "Corgi",
    secondary_breed: "",
    cross_breed: true,
    color: "Brown",
    coat_type: "Short",
    size: "Medium",
    location: "Tarampa, West Brisbane",
    friendly_with: "Dogs (MUST be a calm well balanced dog) and cats (can sometimes get over excited and chase). Kids not recommended.",
    would_suit: "Couple, singles, retirees, families",
    weight: 8,
    behavior_notes: "Needs a confident dog owner as he can be snappy",
    medical_notes: "",
    house_trained: true,
    adoption_fee: 450,
    bin: "BIN0000561500753",
    desexed: true,
    vaccinated: true,
    wormed: true,
    heartworm_treated: true,
    dob: 21/01/2019,
    extra_notes: "",
    description: "Budweiser, or Buddy as he is known always greets you with great excitement when you get home"
    },

    {
    user_id: "",
    animal_photo: "http://lorempixel.com/200/200",
    animal_type: "Cat",
    microchip: "abc987654321",
    name: "Abbey",
    age: 9,
    gender: "Female",
    primary_breed: "Bengal",
    secondary_breed: "",
    cross_breed: false,
    color: "Brown spotted",
    coat_type: "Short",
    size: "Small",
    location: "Wakerley, Brisbane",
    friendly_with: "None, must be only cat",
    would_suit: "Couple, singles, retirees, families",
    weight: 4,
    behavior_notes: "Needs an experienced owner",
    medical_notes: "Sensitive skin",
    house_trained: true,
    adoption_fee: 250,
    bin: "BIN0000561500753",
    desexed: true,
    vaccinated: true,
    wormed: true,
    heartworm_treated: true,
    dob: 21/01/2010,
    extra_notes: "",
    description: "Brown spotted Bangel cat"
    }
]

animalData.forEach(doc => {
    model.createOne(doc)
})